#!/bin/bash

create_ipa() {
    app_path=$1
    app_name=$2
    mkdir Payload
    cp -R $app_path ./Payload/
    zip -r -q $app_name ./Payload
    rm -r ./Payload
    echo "Converted $app_path to $app_name"
}

create_ipa /Users/hgenev/DerivedData_Xcode/PerfectoSwiftApp-fwgvlcwbxtcagicjerrhutccunes/Build/Products/Debug-iphoneos/PerfectoSwiftApp.app PerfectoSwiftApp.ipa
create_ipa /Users/hgenev/DerivedData_Xcode/PerfectoSwiftApp-fwgvlcwbxtcagicjerrhutccunes/Build/Products/Debug-iphoneos/PerfectoSwiftAppUITests-Runner.app PerfectoSwiftAppUITests-Runner.ipa

# app_path="/Users/hgenev/DerivedData_Xcode/PerfectoSwiftApp-fwgvlcwbxtcagicjerrhutccunes/Build/Products/Debug-iphoneos/PerfectoSwiftApp.app"
# mkdir Payload
# cp -R $app_path ./Payload/
# zip -r PerfectoSwiftApp.ipa ./Payload
# rm -r ./Payload